# Generated by Django 3.0.7 on 2021-06-20 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mpesa_API', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stkpayment',
            name='CheckoutRequestID',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='stkpayment',
            name='MerchantRequestID',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='stkpayment',
            name='ResultDesc',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='stkpayment',
            name='TransactionDate',
            field=models.DateTimeField(max_length=100),
        ),
        migrations.AlterField(
            model_name='stkpayment',
            name='phone_number',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='stkpayment',
            name='transaction_code',
            field=models.TextField(max_length=100),
        ),
    ]
