# Generated by Django 3.2.4 on 2021-06-18 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mpesa_API', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='STKPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('phone_number', models.TextField()),
                ('transaction_Code', models.TextField()),
            ],
            options={
                'verbose_name': 'STK Payment',
                'verbose_name_plural': 'stk Payments',
            },
        ),
    ]
