# Generated by Django 3.2.4 on 2021-06-18 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mpesa_API', '0002_stkpayment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stkpayment',
            old_name='transaction_Code',
            new_name='transaction_code',
        ),
    ]
